name: MyBotBox
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pipeline:
    uses: siri1410/yarlis-portfolio/.github/workflows/_pipeline.yml@main
    with:
      domain: mbx
      project_id: mybotbox-prod
      run_e2e: false
      deploy_staging: true
      deploy_prod: true
      base_url_prod: https://mybotbox.com
    secrets:
      WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
      WIF_SA: ${{ secrets.GCP_WIF_SA_MBX }}
